version: "3.3"

services:

  api:
    build:
      context: .
    image: mikro-hub
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal
  
  products:
    build:
      context: .
    image: mikro-hub
    env_file: docker-compose.env
    environment:
      SERVICES: products
      MONGO_URI: "mongodb://mongo:27017/products"
    depends_on:
      - nats
      - mongo
    networks:
      - internal

  warehouse:
    build:
      context: .
    image: mikro-hub
    env_file: docker-compose.env
    environment:
      SERVICES: warehouse
      MONGO_URI: "mongodb://mongo:27017/warehouse"
    depends_on:
      - nats
      - mongo
    networks:
      - internal

  nats:
    image: nats:2
    networks:
      - internal

  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

  mongo:
    image: mongo:latest
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - internal

networks:
  internal:

volumes:
  data:
